version: "3.9"

services:
  backend:
    image: albaruth/backend:latest 
    container_name: backend
    command: python -m backend
    ports:
      - "8000:8000"
    networks:
      - backend
      - frontend
  frontend:
    image: albaruth/frontend:latest
    stdin_open: true
    command: npm run dev
    ports:
      - '5173:5173'
    networks:
      - frontend

networks:
  backend:
  frontend:
