version: "3.9"

services:
  backend:
    image: Albaruth/backend:latest  # Используем образ из Docker Hub
    container_name: backend
    command: python -m backend
    ports:
      - "8000:8000"
    networks:
      - backend
      - frontend
  frontend:
    image: AlbaRuth/frontend:latest  # Используем образ из Docker Hub
    stdin_open: true
    command: npm run dev
    ports:
      - '5173:5173'
    networks:
      - frontend

networks:
  backend:
  frontend:
